language: java
jdk: oraclejdk8
script:
  - mvn test failsafe:integration-test failsafe:verify -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

deploy:
  provider: script
  script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean source:jar javadoc:jar deploy"
  skip_cleanup: true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"

cache:
  directories:
  - $HOME/.m2
